### ISSUE TITLE
Improvement in user experience

### ISSUE THREAD

**Issue by manubb** [mocnik-science/geogrid.js#1]
While running the example, i notice that the `setTimeout` in `_addWebGL` method:
https://github.com/GIScience/geogrid.js/blob/master/src/geogrid.js#L541
 is apparently useless  and causes flickering on `zoomEnd`.

**Comment by mocnik-science** [comment]
Thanks for naming this issue. The reason for introducing the `setTimeout` has been fallen away. I have fixed the bug.
