### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by CosmosEcho** [mocnik-science/geogrid.js#2]
after 'npm install', I run 'npm run build', there is a error .

\geogrid.js-master\node_modules\webpack-sources\node_modules\source-map\lib\source-map-generator.js:276
        throw new Error(
        ^

Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.

**Comment by CosmosEcho** [comment]
I found the problem. I remove the source-map in webpack.config.js:
  stats: {
    colors: true,
  },
  //devtool: 'source-map',
  plugins: [
    new BibiliPlugin({}),
  ],

**Comment by mocnik-science** [comment]
Thank you for pointing out.  Actually, disabling the source maps works but is not the intended solution.  The problem origins form an error in `webpack-sources`, which I now downgrade manually to version `1.0.1`.  When the error is solved by `webpack-sources`, I will deactivate the old version from the list of required dependencies.
