### ISSUE TITLE
render only visible hexagons

### ISSUE THREAD

**Issue by tyrasd** [mocnik-science/geogrid.js#3]
To improve performance (most notably in the svg rendering backend, but the webgl could also benefit), one should only render the geogrid hexagons that are visible in the current map viewport (plus some margin to allow panning the map). This could be implemented using leaflet's built in [gridlayer](https://leafletjs.com/reference-1.3.0.html#gridlayer) as a basis.

**Comment by mocnik-science** [comment]
should be fixed
