### ISSUE TITLE
expose computeGeoJSON for generic use

### ISSUE THREAD

**Issue by tyrasd** [mocnik-science/geogrid.js#4]
One may just want to generate GeoJSON data from _geogrid_ data, without immediately displaying it on a leaflet map. For this it would be nice to have access to the (for now only internal) method `computeGeoJSON()` or something similar. Also, the library should for this use case not throw an exception if Leaflet or d3 are not loaded. Maybe it makes sense to split the library in two parts: geogrid.js with just the geogrid-to-geojson functions (and maybe some related methods) and another library that is the leaflet pluging (e.g. called leaflet-geogrid.js). What do you think?

related: https://github.com/GIScience/geogrid/issues/2

**Comment by mocnik-science** [comment]
Yes, this idea is very good. As geogrid.js is already published as a leaflet plugin, I could imagine two additional possibilities. Either one publishes the geogrid-to-geojson functionality as "geogrid.js core" and the leaflet plugin as "geogrid.js", or (if one decides that the size of the library does not matter) one could provide the geogrid-to-geojson functionality as abstract functions in geogrid.js itself and first check for dependencies if they are needed. In my opinion, it would make sense to discuss whether geogrid.js should also be extended for other systems like Open Layers.

**Comment by mocnik-science** [comment]
Dear @tyrasd,
I know that this ticket has been open quite along.  Nevertheless, I am happy to now have implemented a corresponding function in 2cc9401:
```javascript
L.isea3hToGeoJSON({data}, geoJSON => console.log(geoJSON))
```
The implementation required a major reorganization but could finally be achieved, also because the library has now been improved considerably with respect to its speed.  Have fun using this function!
