### ISSUE TITLE
Failed to load vptree

### ISSUE THREAD

**Issue by y-luis-rojo** [mocnik-science/geogrid.js#5]
I am trying to use `geogrid.js`, but I am getting the following error on the browser console:

`Failed to load worker script at "http://localhost:8080/libs/vptree.js/vptree.min.js"`

You do not mention this library except for the `urlLibs` at options table. Can you please, crarify about this library? Is [this one](https://github.com/fpirsch/vptree.js/)? Can you include that information in the `README.md`?

Thanks.

**Comment by mocnik-science** [comment]
Thank you for your comment.  Yes, it is the library you point out.  A corresponding comment was clearly missing in the readme.  You should now find it [here](
https://github.com/GIScience/geogrid.js#use-the-library).
